// GENERATED by scripts/build-tokens.mjs from tokens.export.json — DO NOT EDIT.
// Run `npm run build:tokens` after changing the snapshot. CI fails if this file is stale.
//
// The stylesheet is what the UI renders from; this is the same values for the code that cannot
// read a stylesheet — a canvas or WebGL scene, a chart library, an email template.

export const tokens = {
  radius: "0.625rem",
  brand: {
    base: "oklch(0.6792 0.2128 36.53)",
    strong: "oklch(0.52 0.21 36.53)",
  },
  font: {
    sans: 'system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    mono: 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
  },
  duration: {
    fast: "150ms",
    default: "200ms",
    slow: "300ms",
  },
  easing: {
    standard: "cubic-bezier(0.4, 0, 0.2, 1)",
    accelerate: "cubic-bezier(0.4, 0, 1, 1)",
    decelerate: "cubic-bezier(0, 0, 0.2, 1)",
  },
  color: {
    light: {
      background: "oklch(1 0 0)",
      foreground: "oklch(0.145 0 0)",
      card: "oklch(1 0 0)",
      "card-foreground": "oklch(0.145 0 0)",
      popover: "oklch(1 0 0)",
      "popover-foreground": "oklch(0.145 0 0)",
      primary: "oklch(0.6792 0.2128 36.53)",
      "primary-strong": "oklch(0.52 0.21 36.53)",
      "primary-foreground": "oklch(0.145 0 0)",
      secondary: "oklch(0.97 0 0)",
      "secondary-foreground": "oklch(0.205 0 0)",
      muted: "oklch(0.97 0 0)",
      "muted-foreground": "oklch(0.54 0 0)",
      accent: "oklch(0.97 0 0)",
      "accent-foreground": "oklch(0.205 0 0)",
      destructive: "oklch(0.52 0.21 25)",
      "destructive-foreground": "oklch(0.985 0 0)",
      border: "oklch(0.922 0 0)",
      input: "oklch(0.922 0 0)",
      ring: "oklch(0.6792 0.2128 36.53)",
    },
    dark: {
      background: "oklch(0.145 0 0)",
      foreground: "oklch(0.985 0 0)",
      card: "oklch(0.205 0 0)",
      "card-foreground": "oklch(0.985 0 0)",
      popover: "oklch(0.205 0 0)",
      "popover-foreground": "oklch(0.985 0 0)",
      primary: "oklch(0.6792 0.2128 36.53)",
      "primary-strong": "oklch(0.6792 0.2128 36.53)",
      "primary-foreground": "oklch(0.145 0 0)",
      secondary: "oklch(0.269 0 0)",
      "secondary-foreground": "oklch(0.985 0 0)",
      muted: "oklch(0.269 0 0)",
      "muted-foreground": "oklch(0.708 0 0)",
      accent: "oklch(0.269 0 0)",
      "accent-foreground": "oklch(0.985 0 0)",
      destructive: "oklch(0.62 0.2 25)",
      "destructive-foreground": "oklch(0.145 0 0)",
      border: "oklch(1 0 0 / 12%)",
      input: "oklch(1 0 0 / 15%)",
      ring: "oklch(0.6792 0.2128 36.53)",
    },
  },
} as const;

/** "light" | "dark" — the two modes the semantic collection declares. */
export type ThemeName = keyof typeof tokens.color;

/** Every semantic colour token name, e.g. "background" | "primary-foreground". */
export type ColorToken = keyof (typeof tokens.color)["light"];
