/**
 * build-tokens.mjs — tokens.export.json  ->  packages/ui/src/styles/tokens.css
 *                                        ->  packages/ui/src/tokens/tokens.ts
 *
 * Both outputs are GENERATED AND COMMITTED, and CI re-runs this then asserts `git diff` is empty.
 * Committing them means a consumer can read the palette in a diff; regenerating them in CI means
 * the committed copy can never drift from the snapshot it claims to come from.
 *
 * The Quasar/Vue counterpart emits SCSS. This emits Tailwind v4: the same token values, expressed as CSS
 * custom properties plus an `@theme inline` block that turns each one into a utility
 * (`bg-background`, `text-muted-foreground`, `rounded-lg`).
 */
import { writeFileSync } from "node:fs";

import {
  CONSUMED_COLLECTIONS,
  KNOWN_EXTRA_COLLECTIONS,
  PREFIX_MIN,
  ROOT_PRIMITIVES,
  ROOT_PRIMITIVE_BY_PATH,
  SEMANTIC_ORDER,
  TOKENS_CSS,
  TOKENS_TS,
  describe,
  flattenAll,
  loadExport,
  pxToRem,
  resolveCss,
  resolveValue,
} from "./lib/token-schema.mjs";

const doc = loadExport();
const flat = flattenAll(doc);

// ── guards ──────────────────────────────────────────────────────────────────────────────────────
// Run before emitting anything: half a stylesheet is worse than no stylesheet, because it still
// builds.
for (const { col, prefix, min } of PREFIX_MIN) {
  const n = [...flat[col].keys()].filter((k) => k.startsWith(prefix)).length;
  if (n < min) {
    throw new Error(
      `tokens.export.json: "${col}" has ${n} tokens under "${prefix}", expected >= ${min}. ` +
        `A Figma rename usually looks exactly like this.`,
    );
  }
}
for (const name of SEMANTIC_ORDER) {
  if (!flat.semantic.has(`color/${name}`)) {
    throw new Error(`tokens.export.json: semantic colour "color/${name}" is missing`);
  }
}
const unknown = Object.keys(doc.tokens).filter(
  (c) => !CONSUMED_COLLECTIONS.includes(c) && !KNOWN_EXTRA_COLLECTIONS.includes(c),
);
if (unknown.length)
  console.warn(`note: ignoring unknown collection(s): ${unknown.join(", ")}`);

// ── helpers ─────────────────────────────────────────────────────────────────────────────────────
const HEADER = `/* GENERATED by scripts/build-tokens.mjs from tokens.export.json — DO NOT EDIT.
 * Run \`npm run build:tokens\` after changing the snapshot. CI fails if this file is stale.
 */`;

/** A description becomes a block comment above the declaration, or nothing. */
function comment(text, indent = "  ") {
  if (!text) return "";
  const words = text.split(/\s+/);
  const lines = [];
  let line = "";
  for (const w of words) {
    if ((line + " " + w).trim().length > 92) {
      lines.push(line.trim());
      line = w;
    } else {
      line += ` ${w}`;
    }
  }
  if (line.trim()) lines.push(line.trim());
  return (
    `${indent}/* ` +
    lines.join(`\n${indent} * `) +
    (lines.length > 1 ? `\n${indent} */\n` : ` */\n`)
  );
}

/**
 * A semantic colour that merely aliases a root primitive is emitted as `var(--brand)`, not as the
 * resolved literal. That is not cosmetic: it keeps "re-brand by setting one custom property" true
 * at RUNTIME, on any DOM subtree, which a flattened literal would silently take away.
 */
function semanticValue(name, mode) {
  const path = `color/${name}`;
  const { terminal } = resolveValue(flat, "semantic", path, mode);
  const rootVar = ROOT_PRIMITIVE_BY_PATH.get(terminal);
  return rootVar ? `var(${rootVar})` : resolveCss(flat, "semantic", path, mode);
}

const semanticBlock = (mode) =>
  SEMANTIC_ORDER.map((name) => {
    const path = `color/${name}`;
    const value = semanticValue(name, mode);
    // The description belongs to the token, not to a theme, so it is emitted once — on Light.
    const doc = mode === "Light" ? comment(describe(flat, "semantic", path)) : "";
    return `${doc}  --${name}: ${value};`;
  }).join("\n");

const motion = {
  duration: ["fast", "default", "slow"].map((k) => [
    k,
    `${resolveCss(flat, "motion", `duration/${k}`, "Default")}ms`,
  ]),
  easing: ["standard", "accelerate", "decelerate"].map((k) => [
    k,
    resolveCss(flat, "motion", `easing/${k}`, "Default"),
  ]),
};

const fonts = ["sans", "mono"].map((k) => [
  k,
  resolveCss(flat, "typo-base", `typography/font-family/${k}`, "Mode 1"),
]);

const rootPrimitives = ROOT_PRIMITIVES.map(({ css, col, path, as }) => {
  const raw = resolveCss(flat, col, path, "Mode 1");
  const value = as === "rem" ? pxToRem(raw) : raw;
  return `${comment(describe(flat, col, path))}  ${css}: ${value};`;
}).join("\n");

// ── tokens.css ──────────────────────────────────────────────────────────────────────────────────
const css = `${HEADER}

/* Dark mode is a \`.dark\` class on an ancestor — the shape next-themes produces with
 * attribute="class". Declared here because the design system's own components use \`dark:\`
 * utilities, so the variant has to exist wherever they do. */
@custom-variant dark (&:is(.dark *));

:root {
${rootPrimitives}

${motion.duration.map(([k, v]) => `  --duration-${k}: ${v};`).join("\n")}

  /* Semantic colours — Light. */
${semanticBlock("Light")}
}

.dark {
  /* Semantic colours — Dark. Only the theme-dependent tokens are redeclared; --brand, --radius
   * and motion are theme-independent and stay in :root. */
${semanticBlock("Dark")}
}

/* Expose the tokens as Tailwind utilities: bg-background, text-muted-foreground, border,
 * rounded-lg, font-sans, ease-standard. \`inline\` keeps the var() references intact so a
 * consumer can still override a token at any DOM level. */
@theme inline {
${fonts.map(([k, v]) => `  --font-${k}: ${v};`).join("\n")}

  --color-brand: var(--brand);
  --color-brand-strong: var(--brand-strong);
${SEMANTIC_ORDER.map((n) => `  --color-${n}: var(--${n});`).join("\n")}

  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);

${motion.easing.map(([k, v]) => `  --ease-${k}: ${v};`).join("\n")}
}
`;

// ── tokens.ts ───────────────────────────────────────────────────────────────────────────────────
const q = (s) => JSON.stringify(s);
// Literals here, deliberately: a canvas or an email template cannot resolve `var(--brand)`.
const colorObj = (mode) =>
  SEMANTIC_ORDER.map(
    (n) => `    ${q(n)}: ${q(resolveCss(flat, "semantic", `color/${n}`, mode))},`,
  ).join("\n");

const ts = `// GENERATED by scripts/build-tokens.mjs from tokens.export.json — DO NOT EDIT.
// Run \`npm run build:tokens\` after changing the snapshot. CI fails if this file is stale.
//
// The stylesheet is what the UI renders from; this is the same values for the code that cannot
// read a stylesheet — a canvas or WebGL scene, a chart library, an email template.

export const tokens = {
  radius: ${q(pxToRem(resolveCss(flat, "primitives", "border radius/base", "Mode 1")))},
  brand: {
    base: ${q(resolveCss(flat, "primitives", "colors/brand/base", "Mode 1"))},
    strong: ${q(resolveCss(flat, "primitives", "colors/brand/strong", "Mode 1"))},
  },
  font: {
${fonts.map(([k, v]) => `    ${k}: ${q(v)},`).join("\n")}
  },
  duration: {
${motion.duration.map(([k, v]) => `    ${q(k)}: ${q(v)},`).join("\n")}
  },
  easing: {
${motion.easing.map(([k, v]) => `    ${k}: ${q(v)},`).join("\n")}
  },
  color: {
    light: {
${colorObj("Light")}
    },
    dark: {
${colorObj("Dark")}
    },
  },
} as const;

/** "light" | "dark" — the two modes the semantic collection declares. */
export type ThemeName = keyof typeof tokens.color;

/** Every semantic colour token name, e.g. "background" | "primary-foreground". */
export type ColorToken = keyof (typeof tokens.color)["light"];
`;

writeFileSync(TOKENS_CSS, css);
writeFileSync(TOKENS_TS, ts);
console.log(
  `build-tokens: wrote ${SEMANTIC_ORDER.length} semantic colours x 2 modes, ` +
    `${ROOT_PRIMITIVES.length} root primitives, ${motion.duration.length} durations, ` +
    `${motion.easing.length} easings`,
);
