/**
 * build-catalog.mjs — the component sources -> docs/components.md
 *
 * Generated and committed, so the catalog is readable in a diff and on the Git host without
 * building anything. CI regenerates it and asserts the diff is empty, which is what stops it
 * from quietly describing a version of the library that no longer exists.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { catalog } from "./lib/catalog.mjs";
import { ROOT } from "./lib/token-schema.mjs";

const groups = catalog();
const all = groups.flatMap((g) => g.components);

const escape = (s) => s.replace(/\|/g, "\\|");
const code = (s) => `\`${s}\``;

const lines = [
  "<!-- GENERATED by scripts/build-catalog.mjs from the component sources — DO NOT EDIT. -->",
  "<!-- Run `npm run build:catalog`. CI fails if this file is stale. -->",
  "",
  "# Components",
  "",
  `${all.length} components in \`@digitaltwin/design-system\`. Everything below is read out of the`,
  "sources, so it cannot describe a version of the library that does not exist.",
  "",
  '**Server** means the module carries no `"use client"` directive and renders in a React Server',
  "Component without pulling a client reference into the route. That is a property worth keeping:",
  "the build is unbundled precisely so it stays true per file.",
  "",
];

// ── the index ───────────────────────────────────────────────────────────────────────────────────
for (const group of groups) {
  lines.push(`## ${group.title}`, "");
  lines.push("| Component | | What it is | Variants |");
  lines.push("| --- | --- | --- | --- |");
  for (const c of group.components) {
    const scales = c.variants
      ? Object.entries(c.variants)
          .map(([k, v]) => `${k}: ${v.map(code).join(" ")}`)
          .join("<br>")
      : "—";
    lines.push(
      `| [${c.name}](../${c.file}) | ${c.client ? "client" : "**server**"} | ` +
        `${escape(c.description || "—")} | ${scales} |`,
    );
  }
  lines.push("");
}

// ── per-component detail, for the ones that carry a sidecar ─────────────────────────────────────
const documented = all.filter((c) => c.sidecar);
if (documented.length) {
  lines.push("---", "", "## Usage notes", "");
  for (const c of documented) {
    lines.push(`### ${c.name}`, "");
    if (c.sidecar.guidance) lines.push(c.sidecar.guidance, "");
    if (c.sidecar.example) lines.push("```tsx", c.sidecar.example, "```", "");
    if (c.sidecar.notes) lines.push(`> ${c.sidecar.notes}`, "");
    if (c.sidecar.figma) {
      lines.push(
        `Figma: page \`${c.sidecar.figma.page}\`, node \`${c.sidecar.figma.nodeId}\`.`,
        "",
      );
    }
  }
}

// ── exports, so a consumer can find the right name without opening the barrel ───────────────────
lines.push("---", "", "## Exported symbols", "");
lines.push("| Component | Exports |");
lines.push("| --- | --- |");
for (const c of all) {
  lines.push(`| ${c.name} | ${c.exports.map(code).join(" ") || "—"} |`);
}
lines.push("");

writeFileSync(join(ROOT, "docs/components.md"), lines.join("\n"));
console.log(
  `build-catalog: ${all.length} components, ${groups.length} sections, ` +
    `${documented.length} with usage notes`,
);
